[theme]
primaryColor = "#1f77b4"           # A nice blue accent color
backgroundColor = "#FFFFFF"        # White main background
secondaryBackgroundColor = "#F5F5F5"  # Light gray for sidebar/cards
textColor = "#262626"              # Dark gray for good readability
font = "sans serif"                # Clean, professional font
